### ISSUE TITLE
use dotenv

### ISSUE THREAD

**Issue by Amitminer** [DevanshxDop/Iris-Assistant-Template#1]
bro use "dotenv" for configuration. It's better for hiding sensitive data in a ".env" file.🙂
for now you're using
config.json
```yml
"token": "Your Token Here",
 "mongo": "Your Mongo Uri",
 "clientId": "Your Bot Id"
```
